#!/bin/bash
apt-get -y install python3
apt-get -y install python3-setuptools
apt-get -y install python3-sqlalchemy
apt-get -y install python3-pip
apt-get -y install python3-nose
apt-get -y install libftdi-dev
apt-get -y install libusb-1.0-0-dev
apt-get -y install libusb-dev
pip3 install pyudev
pip3 install libusb1
pip3 install pyusb==1.0.0b2
pip3 install pylibftdi
python3 setup.py install
